# Generated by Django 2.2.4 on 2019-08-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QCRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl', models.IntegerField(verbose_name='changelist')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SuiteRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_name', models.CharField(max_length=20)),
                ('platform', models.CharField(choices=[('win7', 'Windows 7'), ('win10', 'Windows 10'), ('rhe71', 'Linux RHEL 7.1')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('num_passed', models.IntegerField(default=0)),
                ('num_error', models.IntegerField(default=0)),
                ('num_failed', models.IntegerField(default=0)),
                ('qc_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc_review.QCRun')),
            ],
        ),
    ]
