# Generated by Django 2.2.4 on 2019-08-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrun',
            name='codeline',
            field=models.CharField(default='ADAMSDEV', max_length=20),
            preserve_default=False,
        ),
    ]
