# Generated by Django 2.2.4 on 2019-08-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_review', '0003_qcrun_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qcrun',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qcrun',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
